/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type Startup = {
  _id: string;
  _type: "startup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  description?: string;
  views?: number;
  category?: string;
  image?: string;
  pitch?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  name?: string;
  username?: string;
  email?: string;
  image?: string;
  bio?: string;
};

export type Markdown = string;

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | SanityAssetSourceData | Startup | Slug | Author | Markdown;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: STARTUP_QUERIES
// Query: *[_type=='startup' && defined(slug.current) && !defined($search) || title match $search || category match $search || author->name match $search] | order(_createdAt desc){            _id,            title,            slug,            description,            author -> {            _id,            name,            bio,            image            },            image,            views,            category,            pitch,            _createdAt        }
export type STARTUP_QUERIESResult = Array<{
  _id: string;
  title: null;
  slug: null;
  description: null;
  author: null;
  image: string | null;
  views: null;
  category: null;
  pitch: null;
  _createdAt: string;
} | {
  _id: string;
  title: string | null;
  slug: null;
  description: string | null;
  author: null;
  image: null;
  views: null;
  category: null;
  pitch: null;
  _createdAt: string;
} | {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  author: {
    _id: string;
    name: string | null;
    bio: string | null;
    image: string | null;
  } | null;
  image: string | null;
  views: number | null;
  category: string | null;
  pitch: string | null;
  _createdAt: string;
}>;
// Variable: STARTUP_BY_ID_QUERY
// Query: *[_type=='startup' && _id match $id][0]{  _id,    _createdAt,  title,    slug,    description,    author -> {      _id,      name,      username,      bio,      image    },    image,    views,    category,    pitch}
export type STARTUP_BY_ID_QUERYResult = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  author: {
    _id: string;
    name: string | null;
    username: string | null;
    bio: string | null;
    image: string | null;
  } | null;
  image: string | null;
  views: number | null;
  category: string | null;
  pitch: string | null;
} | null;
// Variable: STARTUP_VIEWS_BY_ID_QUERY
// Query: *[_type=='startup' && _id match $id][0]{    _id,        views,}
export type STARTUP_VIEWS_BY_ID_QUERYResult = {
  _id: string;
  views: number | null;
} | null;
// Variable: AUTHOR_BY_GITHUB_ID
// Query: *[_type=="author" && id == $id][0]{  _id,    name,    username,    image,    bio}
export type AUTHOR_BY_GITHUB_IDResult = {
  _id: string;
  name: string | null;
  username: string | null;
  image: string | null;
  bio: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type=='startup' && defined(slug.current) && !defined($search) || title match $search || category match $search || author->name match $search] | order(_createdAt desc){\n            _id,\n            title,\n            slug,\n            description,\n            author -> {\n            _id,\n            name,\n            bio,\n            image\n            },\n            image,\n            views,\n            category,\n            pitch,\n            _createdAt\n        }": STARTUP_QUERIESResult;
    "*[_type=='startup' && _id match $id][0]{\n  _id,\n    _createdAt,\n  title,\n    slug,\n    description,\n    author -> {\n      _id,\n      name,\n      username,\n      bio,\n      image\n    },\n    image,\n    views,\n    category,\n    pitch\n}": STARTUP_BY_ID_QUERYResult;
    "*[_type=='startup' && _id match $id][0]{\n    _id,    \n    views,\n}": STARTUP_VIEWS_BY_ID_QUERYResult;
    "*[_type==\"author\" && id == $id][0]{\n  _id,\n    name,\n    username,\n    image,\n    bio\n}": AUTHOR_BY_GITHUB_IDResult;
  }
}
